# Generated by Django 5.2.5 on 2025-10-01 19:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='images/')),
                ('likes', models.IntegerField(default=0)),
                ('description', models.CharField(max_length=100)),
                ('post_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('image_type', models.CharField(choices=[('PR', 'PORTRAIT'), ('LN', 'LANDSCAPE'), ('SF', 'SELFIE'), ('AR', 'ART'), ('DC', 'DOCUMENT'), ('PN', 'PANORAMA')], max_length=2)),
            ],
        ),
    ]
